name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt' 

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Build Spring Boot application
      run: |
        ./mvnw package -DskipTests
      #env:
        #SPRING_PROFILES_ACTIVE: production  # Set your desired Spring profiles

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build . -t zayarlinnnaung/deswithlzw
      env:
        DOCKER_BUILDKIT: 1

    - name: Push Docker image
      run: |
        docker push zayarlinnnaung/deswithlzw